name: Maven Build

on:
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn clean install

      - name: Submit Maven dependencies
        uses: advanced-security/maven-dependency-submission-action@v3
